### ISSUE TITLE
Calendar view bug when scroll down to the bottom

### ISSUE THREAD

**Issue by yijia-cc** [yijia-cc/grouplive#55]
@wl328Weiminli  Hi Weimin, I was testing our web on staging and found a bug that would like you to look into. 

The bug is that when you scroll down the page to the very bottom, the Calendar view will be outside of the framework and covers the menu bar on the top. You can see the screen shot below.

![image](https://user-images.githubusercontent.com/76569613/119736108-1848d280-be32-11eb-9e7b-aba56d57eee0.png)

**Comment by wl328Weiminli** [comment]
CSS z-index problem, already fixed.  Thank you.

![Screen Shot 2021-05-27 at 4 53 58 PM](https://user-images.githubusercontent.com/54866038/119895802-31be4d00-bf0c-11eb-8bc3-ca0054ee0210.jpg)
